### ISSUE TITLE
Brightening ratio

### ISSUE THREAD

**Issue by LonsonZheng** [Liu-haoyue/NER-Net#1]
Great work! I am curious whether the transmittance of the ND filter remains constant during your data capture. If so, does this mean that the brightening ratio of your method is fixed?

**Comment by Liu-haoyue** [comment]
Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.

**Comment by Liu-haoyue** [comment]
> Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.

**Comment by Liu-haoyue** [comment]
> > > Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.
> 
> For night scenes, do you adjust the ISO of the integration camera to make the brightness normal, or is the ground truth for night scenes also relatively dark?

The experimental details for nighttime scenes are described in detail in Supplementary Materials Section 3.1. We captured images with both low ISO and high ISO settings.

**Comment by LonsonZheng** [comment]
> > > > Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.
> > 
> > 
> > For night scenes, do you adjust the ISO of the integration camera to make the brightness normal, or is the ground truth for night scenes also relatively dark?
> 
> The experimental details for nighttime scenes are described in detail in Supplementary Materials Section 3.1. We captured images with both low ISO and high ISO settings.

Sorry, it seems you misunderstood my point. Section 3.1 of your supplementary material describes the testing process, but what I want to ask is whether the GT of nighttime scene you used for training is relatively dark or normally lit?

**Comment by Liu-haoyue** [comment]
> > > > > Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.
> > > 
> > > 
> > > For night scenes, do you adjust the ISO of the integration camera to make the brightness normal, or is the ground truth for night scenes also relatively dark?
> > 
> > 
> > The experimental details for nighttime scenes are described in detail in Supplementary Materials Section 3.1. We captured images with both low ISO and high ISO settings.
> 
> Sorry, it seems you misunderstood my point. Section 3.1 of your supplementary material describes the testing process, but what I want to ask is whether the GT of nighttime scene you used for training is relatively dark or normally lit?

As mentioned in the paper, the dataset was entirely captured during daytime under good lighting conditions, ensuring the quality of the ground truth (GT). In real nighttime dynamic scenes, it is difficult to obtain good GT, so the data captured at night is only used during the testing phase (evaluating reconstruction quality using no-reference metrics) and is not used during the training phase.

**Comment by LonsonZheng** [comment]
> > > > > > Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.
> > > > 
> > > > 
> > > > For night scenes, do you adjust the ISO of the integration camera to make the brightness normal, or is the ground truth for night scenes also relatively dark?
> > > 
> > > 
> > > The experimental details for nighttime scenes are described in detail in Supplementary Materials Section 3.1. We captured images with both low ISO and high ISO settings.
> > 
> > 
> > Sorry, it seems you misunderstood my point. Section 3.1 of your supplementary material describes the testing process, but what I want to ask is whether the GT of nighttime scene you used for training is relatively dark or normally lit?
> 
> As mentioned in the paper, the dataset was entirely captured during daytime under good lighting conditions, ensuring the quality of the ground truth (GT). In real nighttime dynamic scenes, it is difficult to obtain good GT, so the data captured at night is only used during the testing phase (evaluating reconstruction quality using no-reference metrics) and is not used during the training phase.

I see, thank you for your reply!

**Comment by Liu-haoyue** [comment]
> > > > > > > Yes, the ND filter is fixed. We collect data at different times of the day from daytime to evening, so the different illumination levels in the data come from the variations in ambient light.
> > > > > 
> > > > > 
> > > > > For night scenes, do you adjust the ISO of the integration camera to make the brightness normal, or is the ground truth for night scenes also relatively dark?
> > > > 
> > > > 
> > > > The experimental details for nighttime scenes are described in detail in Supplementary Materials Section 3.1. We captured images with both low ISO and high ISO settings.
> > > 
> > > 
> > > Sorry, it seems you misunderstood my point. Section 3.1 of your supplementary material describes the testing process, but what I want to ask is whether the GT of nighttime scene you used for training is relatively dark or normally lit?
> > 
> > 
> > As mentioned in the paper, the dataset was entirely captured during daytime under good lighting conditions, ensuring the quality of the ground truth (GT). In real nighttime dynamic scenes, it is difficult to obtain good GT, so the data captured at night is only used during the testing phase (evaluating reconstruction quality using no-reference metrics) and is not used during the training phase.
> 
> I see, thank you for your reply!

You're welcome！
